spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/video_platform
    driver-class-name: org.postgresql.Driver
    username: video_app
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
